### ISSUE TITLE
Integrate OTR3 with xmpp-client

### ISSUE THREAD

**Issue by olabini** [twstrike/otr3#10]

**Comment by tcz001** [comment]
I've fork a repo to our group, which is [here](https://github.com/twstrike/xmpp-client), will add some infras for dev env

**Comment by tcz001** [comment]
Current stage:
ake is working,
dataMsg is working, 
authenticate can be started, but smp will fail at third message at verifySMP3
We are still not yet mapping our event notification to SecurityChange.

**Comment by olabini** [comment]
Why does the SMP fail?

**Comment by juniorz** [comment]
I'm testing with a conversation between 2 clients (both using our fork).

Client one sent `/otr-auth juniorz@dukgo.com oursharedsecret`, client two crashes. It seems to be a `nil` `c.smp.state`.

**Comment by juniorz** [comment]
When starting the AKE, it fails on the sender with `While processing message from [email]: otr: bad commit MAC in reveal signature message` if the receiver has both Pidgin and xmpp-client running. But the AKE succeeds (with Pidgin), and I'm able to send encrypted messages.

**Comment by juniorz** [comment]
`/otr-auth` is working.

**Comment by tcz001** [comment]
this is basically finished
