### ISSUE TITLE
Make it possible to trigger debug data with ?OTR!! just like libotr

### ISSUE THREAD

**Issue by olabini** [twstrike/otr3#11]

**Comment by juniorz** [comment]
I had started a spike on this (last week) and I was considering using the event handler in a similar way to how we notify errors: the client support debug messages handling by using `WishToHandleDebugMessage` and `HandleDebugMessage`; the user enable debug messages at runtime by sending a magic `?OTR!!` message (which will not be actually sent).

What do you have in mind?

**Comment by olabini** [comment]
No, something much simpler than that. What libotr support is basically if you enter ?OTR! or ?OTR!! in your client, you will get some info dumped about your current connection. So that should be fairly easy to do.

I've also been thinking about implementing Debug versions of all the event handlers to make it easier to see what's going on.

**Comment by olabini** [comment]
This is implemented now.
