### ISSUE TITLE
Offer an API through Channels

### ISSUE THREAD

**Issue by olabini** [twstrike/otr3#13]

**Comment by tdruiva** [comment]
Dumb question: why we would to offer channels?

**Comment by olabini** [comment]
So let's see. We don't really _need_ to offer channels, but it seems to me that channels is a good fit for an IM application in Golang. If we model sending messages to the other IM user with a channel, and receiving messages from another IM user as a channel we receive messages on, it should be very simple to add OTR on top of it, by combining the OTR channels with the regular IM channels.

I don't think xmpp-client does this, because the UI is fundamentally single-threaded. I suspect for making a GUI based client, you want it to be multithreaded by default, and using channels would make that very easy. Makes sense?

**Comment by juniorz** [comment]
I made the same point on yesterday's conversation.

We also thought about low end machines without crypto support in the
hardware, where the encrypt/decrypt might take some more time. They
could benefit from a channel-based approach by allowing the client GUI
to asynchronously add a message to the send channel, without having to
wait until it's sent to allow another message to be written.

**Comment by tdruiva** [comment]
> Makes sense?

Yes.

I just asked because yesterday we was talking about how do we need to build our public interface, also having in mind the channel support and why we want to can give this kind of support.

**Comment by olabini** [comment]
Let's skip this for now. I am not super sure this is a good idea anymore, and if it is, it might be good to have a client that drives the need. We can reopen if we change our minds.
