### ISSUE TITLE
Fix bugs in draft v3 protocol

### ISSUE THREAD

**Issue by olabini** [twstrike/otr3#2]
Specifically around the fragmented messages descriptions there are several inconsistencies and errors.

**Comment by juniorz** [comment]
There's also the issue regarding `ALLOW_V2` and Reveal Signature/Signature messages.

**Comment by juniorz** [comment]
What happens if you receive a new Query message (from another client) after having the AKE completed in the current conversation? You simply restart another AKE?

Should we forget all keys ([our|their][Current|Previous]) in this case?

**Comment by juniorz** [comment]
> Should we forget all keys ([our|their][Current|Previous]) in this case?
This seems to be the right thing to do. We are doing this at the moment.

**Comment by juniorz** [comment]
The spec doesn't mention what should be done if the data message is not corrupted (both signature and counter verification have succeeded as well as message decryption) but one TLV is corrupted.

We assume this will only happen if the message was sent by a malicious/broken client and it is reasonable to stop processing the remaining TLVs after the first broken TLV is found.

**Comment by tcz001** [comment]
Spec don't mention how it should be handled when an instance tag is found incorrect in different ways. We have errors for them now, but do we need to show them during AKE(or just start again)? it seems only dataMsg is enough.

**Comment by olabini** [comment]
Yeah, the spec says that if the instance tag is incorrect the message should be ignored.

**Comment by olabini** [comment]
I have registered bugs in the bug-tracker for most of these issues, and submitted a patch or two as well.
