### ISSUE TITLE
Implement empty data messages (heartbeats) and IGNORE_UNREADABLE flag

### ISSUE THREAD

**Issue by juniorz** [twstrike/otr3#32]
The message should be hidden from the user but we should generate a notification.

**Comment by olabini** [comment]
What is currently missing is that we need to update lastSent all over the place. We also need to set IGNORE_UNREADABLE on some types of messages, and handle it correctly when receiving it.

**Comment by olabini** [comment]
I think IGNORE_UNREADABLE is done, all over the place!
