### ISSUE TITLE
Get rid of []byte

### ISSUE THREAD

**Issue by juniorz** [twstrike/otr3#33]
We use `[]byte` for a lot of different things:

- Incoming messages (both plain/encoded)
- Serialized things (both with/without header)
- Outbound messages (including before/after encoding and before/after adding header)

It is very confusing.

For instance: `receiveDecoded()` gets data from `processDataMessage()`, `maybeHeartbeat()` and `receiveAKE()` and its hard to know if they all return `toSend` with the same meaning for `[]byte`.

**Comment by olabini** [comment]
I think this is done-ish, right?
