### ISSUE TITLE
Fragments numbers in v2 should not have leading zeros

### ISSUE THREAD

**Issue by juniorz** [twstrike/otr3#44]
The example for fragments provided by the V2 of spec has no leading zeroes for the number of pieces, but the same example in the V3 of the spec has leading zeroes.

We are generating the piece number with leading zeroes for both versions. It makes me wonder if this could break compatibility with some strict-V2 implementation - or if this should be reported as a bug in the spec.

**Comment by olabini** [comment]
We will do the same thing as libotr in this situation, which is:
		    "?OTR,%05hu,%05hu,%s,", (unsigned short)curfrag,
			    (unsigned short)fragment_count, fragdata);

We should add it as a question for the protocol description though.
