### ISSUE TITLE
Checking of the top half counter should be based on unique combination of sender and receiver key IDs

### ISSUE THREAD

**Issue by olabini** [twstrike/otr3#45]
According to the spec:
"Check that the counter in the Data message is strictly larger than the last counter you saw using this pair of keys"

We don't care about the pair of keys. Thus, a message composed of (senderKeyid, receiverKeyid, ctr), these are all valid message progressions:
(1, 1, 1)
(1, 1, 2)
(2, 2, 1)

This is a blocker for us right now, since it stops us from receiving more than one data message.

**Comment by tcz001** [comment]
4ca4b85aa35ef9641dae77ed498b86fd155ae76b

**Comment by olabini** [comment]
Good work by Iván, Reinaldo and Fan!
