### ISSUE TITLE
The MessageEventConnectionEnded is not emitted when the other peer closes the connection.

### ISSUE THREAD

**Issue by juniorz** [twstrike/otr3#50]
The doc for `MessageEventConnectionEnded` says:

> ConversationEnded indicates that the peer ended the secure conversation.

However it is only emitted when we (not the other peer) send a message while the OTR conversation has finished. We might be using it wrongly in `coy` (see twstrike/coyim#128), but this is misleading at least.

**Comment by juniorz** [comment]
I was reading the wrong thing.

**Comment by olabini** [comment]
????

**Comment by juniorz** [comment]
I was pretty much crazy.

**Comment by olabini** [comment]
And that is different from normal how, exactly? =)

**Comment by juniorz** [comment]
The comment for MessageEventConnectionEnded is correct. The thing I wrote in the issue is the comment for another event.
